/*******************************************************************************
**
**  PALETTE CONSTANTS
**
*******************************************************************************/

DEF NUMBER_OF_PALLETE_BYTES     EQU 8


RSRESET

DEF PALETTE_COLOR_WHITE         RB
DEF PALETTE_COLOR_RED           RB
DEF PALETTE_COLOR_GREEN         RB
DEF PALETTE_COLOR_BLUE          RB
DEF PALETTE_COLOR_YELLOW        RB
DEF PALETTE_COLOR_ORANGE        RB
DEF PALETTE_COLOR_CYAN          RB
DEF PALETTE_COLOR_MAGENTA       RB

DEF NUMBER_OF_PALLETE_COLORS    RB 0
