INCLUDE "libraries/hardware.inc/hardware.inc"
    rev_Check_hardware_inc 4.9.1

INCLUDE "libraries/gbc-engine-core/gbc-engine-core-macros.inc"
    gbc_engine_core_version 1.4.2

/*******************************************************************************
**
**  CHARMAPS
**
*******************************************************************************/

INCLUDE "includes/charmaps/charmaps.inc"


/*******************************************************************************
**
**  CONSTANTS
**
*******************************************************************************/

INCLUDE "includes/constants/constants.inc"


/*******************************************************************************
**
**  MACROS
**
*******************************************************************************/

INCLUDE "includes/macros/macros.inc"
